-- SunsetScore V2.2.2 baseline. Run 001 -> 002 -> 003 for a fresh database.
CREATE TABLE IF NOT EXISTS sunset_feedback (
  id TEXT PRIMARY KEY,
  query_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  created_at_local TEXT,
  city TEXT NOT NULL,
  country TEXT,
  admin1 TEXT,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  timezone TEXT,
  sunset_time_local TEXT,
  sunset_azimuth REAL,
  twilight_minutes INTEGER,
  best_viewing_window TEXT,
  model_version TEXT NOT NULL,
  predicted_score INTEGER NOT NULL,
  predicted_level TEXT NOT NULL,
  baseline_score INTEGER,
  baseline_level TEXT,
  regime_label TEXT,
  regime_strength REAL,
  sky_evolution_state TEXT,
  sky_evolution_factor REAL,
  gw_factor REAL,
  comp_sky_canvas INTEGER,
  comp_horizon INTEGER,
  comp_illumination INTEGER,
  comp_atmosphere INTEGER,
  comp_weather INTEGER,
  cloud_cover_total INTEGER,
  cloud_cover_low INTEGER,
  cloud_cover_mid INTEGER,
  cloud_cover_high INTEGER,
  corridor_cloud_mid REAL,
  corridor_cloud_high REAL,
  anti_sunset_score INTEGER,
  spatial_variance REAL,
  cloud_continuity INTEGER,
  aod REAL,
  pm25 REAL,
  humidity REAL,
  surface_pressure REAL,
  visibility_km REAL,
  precipitation REAL,
  layer_wind_850_speed REAL,
  layer_wind_850_dir REAL,
  layer_wind_700_speed REAL,
  layer_wind_700_dir REAL,
  layer_wind_500_speed REAL,
  layer_wind_500_dir REAL,
  is_real_sounding INTEGER DEFAULT 1,
  open_prob_30m REAL,
  open_prob_60m REAL,
  open_prob_120m REAL,
  arrival_risk_30m REAL,
  arrival_risk_60m REAL,
  tile_radar_available INTEGER DEFAULT 0,
  tile_sat_available INTEGER DEFAULT 0,
  dyn_weight_canvas REAL,
  dyn_weight_horizon REAL,
  dyn_weight_illum REAL,
  dyn_weight_atmo REAL,
  dyn_weight_weather REAL,
  user_rating TEXT NOT NULL,
  user_rating_label TEXT NOT NULL,
  user_comment TEXT,
  user_ip_hash TEXT,
  client_ua TEXT,
  raw_snapshot_json TEXT
);

CREATE INDEX IF NOT EXISTS idx_fb_city ON sunset_feedback(city);
CREATE INDEX IF NOT EXISTS idx_fb_created ON sunset_feedback(created_at);
CREATE INDEX IF NOT EXISTS idx_fb_rating ON sunset_feedback(user_rating);
CREATE INDEX IF NOT EXISTS idx_fb_model_ver ON sunset_feedback(model_version);
CREATE INDEX IF NOT EXISTS idx_fb_score ON sunset_feedback(predicted_score);
